// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/m0-foundation/solana-m/services/api/sdk-go/core"
	events "github.com/m0-foundation/solana-m/services/api/sdk-go/events"
	extensions "github.com/m0-foundation/solana-m/services/api/sdk-go/extensions"
	internal "github.com/m0-foundation/solana-m/services/api/sdk-go/internal"
	option "github.com/m0-foundation/solana-m/services/api/sdk-go/option"
	swap "github.com/m0-foundation/solana-m/services/api/sdk-go/swap"
	tokenaccount "github.com/m0-foundation/solana-m/services/api/sdk-go/tokenaccount"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Events       *events.Client
	Extensions   *extensions.Client
	Swap         *swap.Client
	TokenAccount *tokenaccount.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:       options.ToHeader(),
		Events:       events.NewClient(opts...),
		Extensions:   extensions.NewClient(opts...),
		Swap:         swap.NewClient(opts...),
		TokenAccount: tokenaccount.NewClient(opts...),
	}
}
