// Code generated by Fern. DO NOT EDIT.

package extensions

import (
	context "context"
	sdkgo "github.com/m0-foundation/solana-m/services/api/sdk-go"
	core "github.com/m0-foundation/solana-m/services/api/sdk-go/core"
	internal "github.com/m0-foundation/solana-m/services/api/sdk-go/internal"
	option "github.com/m0-foundation/solana-m/services/api/sdk-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Get all extensions
func (c *Client) Extensions(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdkgo.Extensions, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api-production-0046.up.railway.app",
	)
	endpointURL := baseURL + "/extensions/"
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)

	var response *sdkgo.Extensions
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
