// Code generated by Fern. DO NOT EDIT.

package solanaapi

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Mainnet  string
	Localnet string
	Devnet   string
}{
	Mainnet:  "https://api-production-0046.up.railway.app",
	Localnet: "http://localhost:5500",
	Devnet:   "https://api-development-065b.up.railway.app",
}
