// Code generated by Fern. DO NOT EDIT.

package solanaapi

import (
	json "encoding/json"
	core "github.com/m0-foundation/solana-m/services/api/sdk-go/core"
)

type InvalidMint struct {
	*core.APIError
	Body *RequestError
}

func (i *InvalidMint) UnmarshalJSON(data []byte) error {
	var body *RequestError
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 404
	i.Body = body
	return nil
}

func (i *InvalidMint) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InvalidMint) Unwrap() error {
	return i.APIError
}

type BadQuoteRequest struct {
	*core.APIError
	Body *SwapRequestError
}

func (b *BadQuoteRequest) UnmarshalJSON(data []byte) error {
	var body *SwapRequestError
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadQuoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadQuoteRequest) Unwrap() error {
	return b.APIError
}

type QuoteError struct {
	*core.APIError
	Body *SwapRequestError
}

func (q *QuoteError) UnmarshalJSON(data []byte) error {
	var body *SwapRequestError
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	q.StatusCode = 500
	q.Body = body
	return nil
}

func (q *QuoteError) MarshalJSON() ([]byte, error) {
	return json.Marshal(q.Body)
}

func (q *QuoteError) Unwrap() error {
	return q.APIError
}

type QuoteNotFound struct {
	*core.APIError
	Body *SwapRequestError
}

func (q *QuoteNotFound) UnmarshalJSON(data []byte) error {
	var body *SwapRequestError
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	q.StatusCode = 404
	q.Body = body
	return nil
}

func (q *QuoteNotFound) MarshalJSON() ([]byte, error) {
	return json.Marshal(q.Body)
}

func (q *QuoteNotFound) Unwrap() error {
	return q.APIError
}

type SimulationFailed struct {
	*core.APIError
	Body *SwapRequestError
}

func (s *SimulationFailed) UnmarshalJSON(data []byte) error {
	var body *SwapRequestError
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.StatusCode = 400
	s.Body = body
	return nil
}

func (s *SimulationFailed) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

func (s *SimulationFailed) Unwrap() error {
	return s.APIError
}
