// Code generated by Fern. DO NOT EDIT.

package solanaapi

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/m0-foundation/solana-m/services/api/sdk-go/internal"
)

type Extension struct {
	Mint          string  `json:"mint" url:"mint"`
	ProgramId     string  `json:"programId" url:"programId"`
	Symbol        string  `json:"symbol" url:"symbol"`
	Name          string  `json:"name" url:"name"`
	Icon          string  `json:"icon" url:"icon"`
	MVault        string  `json:"mVault" url:"mVault"`
	MVaultBalance float64 `json:"mVaultBalance" url:"mVaultBalance"`
	MEarned       float64 `json:"mEarned" url:"mEarned"`
	TokenSupply   float64 `json:"tokenSupply" url:"tokenSupply"`
	UiMultiplier  float64 `json:"uiMultiplier" url:"uiMultiplier"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *Extension) GetMint() string {
	if e == nil {
		return ""
	}
	return e.Mint
}

func (e *Extension) GetProgramId() string {
	if e == nil {
		return ""
	}
	return e.ProgramId
}

func (e *Extension) GetSymbol() string {
	if e == nil {
		return ""
	}
	return e.Symbol
}

func (e *Extension) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *Extension) GetIcon() string {
	if e == nil {
		return ""
	}
	return e.Icon
}

func (e *Extension) GetMVault() string {
	if e == nil {
		return ""
	}
	return e.MVault
}

func (e *Extension) GetMVaultBalance() float64 {
	if e == nil {
		return 0
	}
	return e.MVaultBalance
}

func (e *Extension) GetMEarned() float64 {
	if e == nil {
		return 0
	}
	return e.MEarned
}

func (e *Extension) GetTokenSupply() float64 {
	if e == nil {
		return 0
	}
	return e.TokenSupply
}

func (e *Extension) GetUiMultiplier() float64 {
	if e == nil {
		return 0
	}
	return e.UiMultiplier
}

func (e *Extension) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *Extension) UnmarshalJSON(data []byte) error {
	type unmarshaler Extension
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = Extension(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *Extension) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type Extensions struct {
	Extensions []*Extension `json:"extensions" url:"extensions"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *Extensions) GetExtensions() []*Extension {
	if e == nil {
		return nil
	}
	return e.Extensions
}

func (e *Extensions) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *Extensions) UnmarshalJSON(data []byte) error {
	type unmarshaler Extensions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = Extensions(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *Extensions) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}
