// Code generated by Fern. DO NOT EDIT.

package solanaapi

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/m0-foundation/solana-m/services/api/sdk-go/internal"
)

type GetQuoteRequest struct {
	InputMint   string `json:"-" url:"inputMint"`
	OutputMint  string `json:"-" url:"outputMint"`
	Amount      string `json:"-" url:"amount"`
	SlippageBps *int   `json:"-" url:"slippageBps,omitempty"`
}

type GetSwapRequest struct {
	QuoteId       string `json:"-" url:"quoteId"`
	UserPublicKey string `json:"-" url:"userPublicKey"`
}

type Quote struct {
	QuoteId        string       `json:"quoteId" url:"quoteId"`
	InputMint      string       `json:"inputMint" url:"inputMint"`
	InAmount       string       `json:"inAmount" url:"inAmount"`
	OutputMint     string       `json:"outputMint" url:"outputMint"`
	OutAmount      string       `json:"outAmount" url:"outAmount"`
	SlippageBps    int          `json:"slippageBps" url:"slippageBps"`
	PriceImpactPct string       `json:"priceImpactPct" url:"priceImpactPct"`
	RoutePlan      []*RoutePlan `json:"routePlan" url:"routePlan"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *Quote) GetQuoteId() string {
	if q == nil {
		return ""
	}
	return q.QuoteId
}

func (q *Quote) GetInputMint() string {
	if q == nil {
		return ""
	}
	return q.InputMint
}

func (q *Quote) GetInAmount() string {
	if q == nil {
		return ""
	}
	return q.InAmount
}

func (q *Quote) GetOutputMint() string {
	if q == nil {
		return ""
	}
	return q.OutputMint
}

func (q *Quote) GetOutAmount() string {
	if q == nil {
		return ""
	}
	return q.OutAmount
}

func (q *Quote) GetSlippageBps() int {
	if q == nil {
		return 0
	}
	return q.SlippageBps
}

func (q *Quote) GetPriceImpactPct() string {
	if q == nil {
		return ""
	}
	return q.PriceImpactPct
}

func (q *Quote) GetRoutePlan() []*RoutePlan {
	if q == nil {
		return nil
	}
	return q.RoutePlan
}

func (q *Quote) GetExtraProperties() map[string]interface{} {
	return q.extraProperties
}

func (q *Quote) UnmarshalJSON(data []byte) error {
	type unmarshaler Quote
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = Quote(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *Quote) String() string {
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

type RoutePlan struct {
	Percent  int       `json:"percent" url:"percent"`
	SwapInfo *SwapInfo `json:"swapInfo" url:"swapInfo"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RoutePlan) GetPercent() int {
	if r == nil {
		return 0
	}
	return r.Percent
}

func (r *RoutePlan) GetSwapInfo() *SwapInfo {
	if r == nil {
		return nil
	}
	return r.SwapInfo
}

func (r *RoutePlan) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RoutePlan) UnmarshalJSON(data []byte) error {
	type unmarshaler RoutePlan
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RoutePlan(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RoutePlan) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type Swap struct {
	Transaction    string   `json:"transaction" url:"transaction"`
	SimulationLogs []string `json:"simulationLogs" url:"simulationLogs"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Swap) GetTransaction() string {
	if s == nil {
		return ""
	}
	return s.Transaction
}

func (s *Swap) GetSimulationLogs() []string {
	if s == nil {
		return nil
	}
	return s.SimulationLogs
}

func (s *Swap) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *Swap) UnmarshalJSON(data []byte) error {
	type unmarshaler Swap
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = Swap(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Swap) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SwapInfo struct {
	AmmKey     string `json:"ammKey" url:"ammKey"`
	Label      string `json:"label" url:"label"`
	InputMint  string `json:"inputMint" url:"inputMint"`
	OutputMint string `json:"outputMint" url:"outputMint"`
	InAmount   string `json:"inAmount" url:"inAmount"`
	OutAmount  string `json:"outAmount" url:"outAmount"`
	FeeAmount  string `json:"feeAmount" url:"feeAmount"`
	FeeMint    string `json:"feeMint" url:"feeMint"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SwapInfo) GetAmmKey() string {
	if s == nil {
		return ""
	}
	return s.AmmKey
}

func (s *SwapInfo) GetLabel() string {
	if s == nil {
		return ""
	}
	return s.Label
}

func (s *SwapInfo) GetInputMint() string {
	if s == nil {
		return ""
	}
	return s.InputMint
}

func (s *SwapInfo) GetOutputMint() string {
	if s == nil {
		return ""
	}
	return s.OutputMint
}

func (s *SwapInfo) GetInAmount() string {
	if s == nil {
		return ""
	}
	return s.InAmount
}

func (s *SwapInfo) GetOutAmount() string {
	if s == nil {
		return ""
	}
	return s.OutAmount
}

func (s *SwapInfo) GetFeeAmount() string {
	if s == nil {
		return ""
	}
	return s.FeeAmount
}

func (s *SwapInfo) GetFeeMint() string {
	if s == nil {
		return ""
	}
	return s.FeeMint
}

func (s *SwapInfo) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SwapInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler SwapInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SwapInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SwapInfo) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SwapRequestError struct {
	Message string   `json:"message" url:"message"`
	Logs    []string `json:"logs,omitempty" url:"logs,omitempty"`
	B64     *string  `json:"b64,omitempty" url:"b64,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SwapRequestError) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *SwapRequestError) GetLogs() []string {
	if s == nil {
		return nil
	}
	return s.Logs
}

func (s *SwapRequestError) GetB64() *string {
	if s == nil {
		return nil
	}
	return s.B64
}

func (s *SwapRequestError) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SwapRequestError) UnmarshalJSON(data []byte) error {
	type unmarshaler SwapRequestError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SwapRequestError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SwapRequestError) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
