// Code generated by Fern. DO NOT EDIT.

package transactions

import (
	context "context"
	sdkgo "github.com/m0-foundation/solana-m/services/api/sdk-go"
	core "github.com/m0-foundation/solana-m/services/api/sdk-go/core"
	internal "github.com/m0-foundation/solana-m/services/api/sdk-go/internal"
	option "github.com/m0-foundation/solana-m/services/api/sdk-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Get swap quote
func (c *Client) Quote(
	ctx context.Context,
	request *sdkgo.GetQuoteRequest,
	opts ...option.RequestOption,
) (*sdkgo.Quote, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api-production-0046.up.railway.app",
	)
	endpointURL := baseURL + "/transactions/quote"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		500: func(apiError *core.APIError) error {
			return &sdkgo.QuoteError{
				APIError: apiError,
			}
		},
		400: func(apiError *core.APIError) error {
			return &sdkgo.BadQuoteRequest{
				APIError: apiError,
			}
		},
	}

	var response *sdkgo.Quote
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Get swap transaction
func (c *Client) Swap(
	ctx context.Context,
	request *sdkgo.GetSwapRequest,
	opts ...option.RequestOption,
) (*sdkgo.Transaction, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api-production-0046.up.railway.app",
	)
	endpointURL := baseURL + "/transactions/swap"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		404: func(apiError *core.APIError) error {
			return &sdkgo.QuoteNotFound{
				APIError: apiError,
			}
		},
		400: func(apiError *core.APIError) error {
			return &sdkgo.SimulationFailed{
				APIError: apiError,
			}
		},
	}

	var response *sdkgo.Transaction
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Get bridge transaction
func (c *Client) Bridge(
	ctx context.Context,
	request *sdkgo.GetBridgeRequest,
	opts ...option.RequestOption,
) (*sdkgo.Transaction, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api-production-0046.up.railway.app",
	)
	endpointURL := baseURL + "/transactions/bridge"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		400: func(apiError *core.APIError) error {
			return &sdkgo.SimulationFailed{
				APIError: apiError,
			}
		},
	}

	var response *sdkgo.Transaction
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
