// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenTransactions {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<TokenTransaction>,
    #[prost(string, tag="2")]
    pub blockhash: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub slot: u64,
    #[prost(int64, tag="4")]
    pub block_time: i64,
    #[prost(uint64, tag="5")]
    pub block_height: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenTransaction {
    #[prost(string, tag="1")]
    pub signature: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub balance_updates: ::prost::alloc::vec::Vec<TokenBalanceUpdate>,
    #[prost(message, repeated, tag="3")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenBalanceUpdate {
    #[prost(string, tag="1")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub mint: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub pre_balance: u64,
    #[prost(uint64, tag="5")]
    pub post_balance: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(string, tag="1")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub instruction: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof="instruction::Update", tags="10, 11, 12, 13")]
    pub update: ::core::option::Option<instruction::Update>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Update {
        #[prost(message, tag="10")]
        IndexUpdate(super::IndexUpdate),
        #[prost(message, tag="11")]
        Claim(super::Claim),
        #[prost(message, tag="12")]
        BridgeEvent(super::BridgeEvent),
        #[prost(message, tag="13")]
        IndexUpdateV2(super::IndexUpdateV2),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IndexUpdate {
    #[prost(uint64, tag="1")]
    pub index: u64,
    #[prost(uint64, tag="2")]
    pub ts: u64,
    #[prost(uint64, tag="3")]
    pub token_supply: u64,
    #[prost(uint64, tag="4")]
    pub max_yield: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IndexUpdateV2 {
    #[prost(uint64, tag="1")]
    pub index: u64,
    #[prost(uint64, tag="2")]
    pub ts: u64,
    #[prost(uint64, tag="3")]
    pub token_supply: u64,
    #[prost(double, tag="4")]
    pub current_multiplier: f64,
    #[prost(double, tag="5")]
    pub new_multiplier: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Claim {
    #[prost(string, tag="1")]
    pub token_account: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub recipient_token_account: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub amount: u64,
    #[prost(uint64, tag="4")]
    pub manager_fee: u64,
    #[prost(uint64, tag="5")]
    pub index: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BridgeEvent {
    #[prost(int64, tag="1")]
    pub amount: i64,
    #[prost(uint64, tag="2")]
    pub token_supply: u64,
    #[prost(bytes="vec", tag="3")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub chain: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
